version: "3.5"
services:
  master:
    build:
      context: .
      shm_size: '2gb'
      args:
        FORMAT_NAMENODE_COMMAND: hdfs namenode -format
    container_name: master
    networks:
      default:
        ipv4_address: 172.10.0.2
    command: bash -c  "start-dfs.sh && start-yarn.sh && mr-jobhistory-daemon.sh start historyserver && start-hbase.sh && tail -f /dev/null"
    ports:
      - 50070:50070
      - 8088:8088
      - 8080:8080
      - 4040:4040
      - 16010:16010
    hostname: master
    restart: always
networks:
  default:
      external:
        name: hadoop-network